// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: signage.proto

package signageproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Display_GetInfo_FullMethodName           = "/io.gosicp.gosignage.v1.Display/GetInfo"
	Display_Health_FullMethodName            = "/io.gosicp.gosignage.v1.Display/Health"
	Display_LoadImage_FullMethodName         = "/io.gosicp.gosignage.v1.Display/LoadImage"
	Display_Refresh_FullMethodName           = "/io.gosicp.gosignage.v1.Display/Refresh"
	Display_Sleep_FullMethodName             = "/io.gosicp.gosignage.v1.Display/Sleep"
	Display_Standby_FullMethodName           = "/io.gosicp.gosignage.v1.Display/Standby"
	Display_SetPullMode_FullMethodName       = "/io.gosicp.gosignage.v1.Display/SetPullMode"
	Display_GetPullMode_FullMethodName       = "/io.gosicp.gosignage.v1.Display/GetPullMode"
	Display_Rotate_FullMethodName            = "/io.gosicp.gosignage.v1.Display/Rotate"
	Display_ReissueClientCert_FullMethodName = "/io.gosicp.gosignage.v1.Display/ReissueClientCert"
	Display_GetMetrics_FullMethodName        = "/io.gosicp.gosignage.v1.Display/GetMetrics"
)

// DisplayClient is the client API for Display service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Display drives a GoodDisplay e-paper panel via an IT8951 controller over
// SPI. It runs on each Pi (push direction).
//
// Authentication: every RPC must carry an `authorization: Bearer <token>`
// header in metadata. The token is generated and printed by the server at
// first launch.
//
// Transport: TLS 1.2+ with a server-presented self-signed certificate
// generated and persisted at first launch. Clients trust the certificate
// explicitly (--cert) or pin its SHA-256 fingerprint.
type DisplayClient interface {
	GetInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DisplayInfo, error)
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	LoadImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LoadImageChunk, LoadImageResponse], error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error)
	Sleep(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Standby(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetPullMode(ctx context.Context, in *SetPullModeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPullMode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PullModeStatus, error)
	Rotate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RotateResponse, error)
	ReissueClientCert(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReissueClientCertResponse, error)
	GetMetrics(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMetricsResponse, error)
}

type displayClient struct {
	cc grpc.ClientConnInterface
}

func NewDisplayClient(cc grpc.ClientConnInterface) DisplayClient {
	return &displayClient{cc}
}

func (c *displayClient) GetInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DisplayInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisplayInfo)
	err := c.cc.Invoke(ctx, Display_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Display_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) LoadImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LoadImageChunk, LoadImageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Display_ServiceDesc.Streams[0], Display_LoadImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LoadImageChunk, LoadImageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Display_LoadImageClient = grpc.ClientStreamingClient[LoadImageChunk, LoadImageResponse]

func (c *displayClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshResponse)
	err := c.cc.Invoke(ctx, Display_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) Sleep(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Display_Sleep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) Standby(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Display_Standby_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) SetPullMode(ctx context.Context, in *SetPullModeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Display_SetPullMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) GetPullMode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PullModeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullModeStatus)
	err := c.cc.Invoke(ctx, Display_GetPullMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) Rotate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RotateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateResponse)
	err := c.cc.Invoke(ctx, Display_Rotate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) ReissueClientCert(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReissueClientCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReissueClientCertResponse)
	err := c.cc.Invoke(ctx, Display_ReissueClientCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *displayClient) GetMetrics(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, Display_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DisplayServer is the server API for Display service.
// All implementations must embed UnimplementedDisplayServer
// for forward compatibility.
//
// Display drives a GoodDisplay e-paper panel via an IT8951 controller over
// SPI. It runs on each Pi (push direction).
//
// Authentication: every RPC must carry an `authorization: Bearer <token>`
// header in metadata. The token is generated and printed by the server at
// first launch.
//
// Transport: TLS 1.2+ with a server-presented self-signed certificate
// generated and persisted at first launch. Clients trust the certificate
// explicitly (--cert) or pin its SHA-256 fingerprint.
type DisplayServer interface {
	GetInfo(context.Context, *emptypb.Empty) (*DisplayInfo, error)
	Health(context.Context, *emptypb.Empty) (*HealthResponse, error)
	LoadImage(grpc.ClientStreamingServer[LoadImageChunk, LoadImageResponse]) error
	Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error)
	Sleep(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	Standby(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	SetPullMode(context.Context, *SetPullModeRequest) (*emptypb.Empty, error)
	GetPullMode(context.Context, *emptypb.Empty) (*PullModeStatus, error)
	Rotate(context.Context, *emptypb.Empty) (*RotateResponse, error)
	ReissueClientCert(context.Context, *emptypb.Empty) (*ReissueClientCertResponse, error)
	GetMetrics(context.Context, *emptypb.Empty) (*GetMetricsResponse, error)
	mustEmbedUnimplementedDisplayServer()
}

// UnimplementedDisplayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDisplayServer struct{}

func (UnimplementedDisplayServer) GetInfo(context.Context, *emptypb.Empty) (*DisplayInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedDisplayServer) Health(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedDisplayServer) LoadImage(grpc.ClientStreamingServer[LoadImageChunk, LoadImageResponse]) error {
	return status.Error(codes.Unimplemented, "method LoadImage not implemented")
}
func (UnimplementedDisplayServer) Refresh(context.Context, *RefreshRequest) (*RefreshResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedDisplayServer) Sleep(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Sleep not implemented")
}
func (UnimplementedDisplayServer) Standby(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Standby not implemented")
}
func (UnimplementedDisplayServer) SetPullMode(context.Context, *SetPullModeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPullMode not implemented")
}
func (UnimplementedDisplayServer) GetPullMode(context.Context, *emptypb.Empty) (*PullModeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPullMode not implemented")
}
func (UnimplementedDisplayServer) Rotate(context.Context, *emptypb.Empty) (*RotateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rotate not implemented")
}
func (UnimplementedDisplayServer) ReissueClientCert(context.Context, *emptypb.Empty) (*ReissueClientCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReissueClientCert not implemented")
}
func (UnimplementedDisplayServer) GetMetrics(context.Context, *emptypb.Empty) (*GetMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedDisplayServer) mustEmbedUnimplementedDisplayServer() {}
func (UnimplementedDisplayServer) testEmbeddedByValue()                 {}

// UnsafeDisplayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DisplayServer will
// result in compilation errors.
type UnsafeDisplayServer interface {
	mustEmbedUnimplementedDisplayServer()
}

func RegisterDisplayServer(s grpc.ServiceRegistrar, srv DisplayServer) {
	// If the following call panics, it indicates UnimplementedDisplayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Display_ServiceDesc, srv)
}

func _Display_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).GetInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_LoadImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DisplayServer).LoadImage(&grpc.GenericServerStream[LoadImageChunk, LoadImageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Display_LoadImageServer = grpc.ClientStreamingServer[LoadImageChunk, LoadImageResponse]

func _Display_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_Sleep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).Sleep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_Sleep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).Sleep(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_Standby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).Standby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_Standby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).Standby(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_SetPullMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPullModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).SetPullMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_SetPullMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).SetPullMode(ctx, req.(*SetPullModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_GetPullMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).GetPullMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_GetPullMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).GetPullMode(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_Rotate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).Rotate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_Rotate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).Rotate(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_ReissueClientCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).ReissueClientCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_ReissueClientCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).ReissueClientCert(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Display_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisplayServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Display_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisplayServer).GetMetrics(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Display_ServiceDesc is the grpc.ServiceDesc for Display service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Display_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.gosicp.gosignage.v1.Display",
	HandlerType: (*DisplayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _Display_GetInfo_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Display_Health_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _Display_Refresh_Handler,
		},
		{
			MethodName: "Sleep",
			Handler:    _Display_Sleep_Handler,
		},
		{
			MethodName: "Standby",
			Handler:    _Display_Standby_Handler,
		},
		{
			MethodName: "SetPullMode",
			Handler:    _Display_SetPullMode_Handler,
		},
		{
			MethodName: "GetPullMode",
			Handler:    _Display_GetPullMode_Handler,
		},
		{
			MethodName: "Rotate",
			Handler:    _Display_Rotate_Handler,
		},
		{
			MethodName: "ReissueClientCert",
			Handler:    _Display_ReissueClientCert_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _Display_GetMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LoadImage",
			Handler:       _Display_LoadImage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "signage.proto",
}

const (
	Content_GetFrame_FullMethodName     = "/io.gosicp.gosignage.v1.Content/GetFrame"
	Content_ReportStatus_FullMethodName = "/io.gosicp.gosignage.v1.Content/ReportStatus"
)

// ContentClient is the client API for Content service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Content is the central rendering server. Pi agents pull frames from it
// when configured in pull mode (push direction always remains available
// via Display.LoadImage/Refresh).
type ContentClient interface {
	GetFrame(ctx context.Context, in *GetFrameRequest, opts ...grpc.CallOption) (*GetFrameResponse, error)
	ReportStatus(ctx context.Context, in *ReportStatusRequest, opts ...grpc.CallOption) (*ReportStatusResponse, error)
}

type contentClient struct {
	cc grpc.ClientConnInterface
}

func NewContentClient(cc grpc.ClientConnInterface) ContentClient {
	return &contentClient{cc}
}

func (c *contentClient) GetFrame(ctx context.Context, in *GetFrameRequest, opts ...grpc.CallOption) (*GetFrameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFrameResponse)
	err := c.cc.Invoke(ctx, Content_GetFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) ReportStatus(ctx context.Context, in *ReportStatusRequest, opts ...grpc.CallOption) (*ReportStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportStatusResponse)
	err := c.cc.Invoke(ctx, Content_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentServer is the server API for Content service.
// All implementations must embed UnimplementedContentServer
// for forward compatibility.
//
// Content is the central rendering server. Pi agents pull frames from it
// when configured in pull mode (push direction always remains available
// via Display.LoadImage/Refresh).
type ContentServer interface {
	GetFrame(context.Context, *GetFrameRequest) (*GetFrameResponse, error)
	ReportStatus(context.Context, *ReportStatusRequest) (*ReportStatusResponse, error)
	mustEmbedUnimplementedContentServer()
}

// UnimplementedContentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentServer struct{}

func (UnimplementedContentServer) GetFrame(context.Context, *GetFrameRequest) (*GetFrameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFrame not implemented")
}
func (UnimplementedContentServer) ReportStatus(context.Context, *ReportStatusRequest) (*ReportStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedContentServer) mustEmbedUnimplementedContentServer() {}
func (UnimplementedContentServer) testEmbeddedByValue()                 {}

// UnsafeContentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentServer will
// result in compilation errors.
type UnsafeContentServer interface {
	mustEmbedUnimplementedContentServer()
}

func RegisterContentServer(s grpc.ServiceRegistrar, srv ContentServer) {
	// If the following call panics, it indicates UnimplementedContentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Content_ServiceDesc, srv)
}

func _Content_GetFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_GetFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetFrame(ctx, req.(*GetFrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).ReportStatus(ctx, req.(*ReportStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Content_ServiceDesc is the grpc.ServiceDesc for Content service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Content_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.gosicp.gosignage.v1.Content",
	HandlerType: (*ContentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFrame",
			Handler:    _Content_GetFrame_Handler,
		},
		{
			MethodName: "ReportStatus",
			Handler:    _Content_ReportStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signage.proto",
}
