// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: signage.proto

package signageproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WaveformMode mirrors the IT8951 controller's display modes. Values match
// the canonical IT8951 firmware mode IDs so the cast in the SPI command is
// a no-op.
type WaveformMode int32

const (
	WaveformMode_WAVEFORM_MODE_UNSPECIFIED WaveformMode = 0
	WaveformMode_WAVEFORM_MODE_INIT        WaveformMode = 1
	WaveformMode_WAVEFORM_MODE_DU          WaveformMode = 2
	WaveformMode_WAVEFORM_MODE_GC16        WaveformMode = 3
	WaveformMode_WAVEFORM_MODE_GL16        WaveformMode = 4
	WaveformMode_WAVEFORM_MODE_GLR16       WaveformMode = 5
	WaveformMode_WAVEFORM_MODE_GLD16       WaveformMode = 6
	WaveformMode_WAVEFORM_MODE_A2          WaveformMode = 7
)

// Enum value maps for WaveformMode.
var (
	WaveformMode_name = map[int32]string{
		0: "WAVEFORM_MODE_UNSPECIFIED",
		1: "WAVEFORM_MODE_INIT",
		2: "WAVEFORM_MODE_DU",
		3: "WAVEFORM_MODE_GC16",
		4: "WAVEFORM_MODE_GL16",
		5: "WAVEFORM_MODE_GLR16",
		6: "WAVEFORM_MODE_GLD16",
		7: "WAVEFORM_MODE_A2",
	}
	WaveformMode_value = map[string]int32{
		"WAVEFORM_MODE_UNSPECIFIED": 0,
		"WAVEFORM_MODE_INIT":        1,
		"WAVEFORM_MODE_DU":          2,
		"WAVEFORM_MODE_GC16":        3,
		"WAVEFORM_MODE_GL16":        4,
		"WAVEFORM_MODE_GLR16":       5,
		"WAVEFORM_MODE_GLD16":       6,
		"WAVEFORM_MODE_A2":          7,
	}
)

func (x WaveformMode) Enum() *WaveformMode {
	p := new(WaveformMode)
	*p = x
	return p
}

func (x WaveformMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WaveformMode) Descriptor() protoreflect.EnumDescriptor {
	return file_signage_proto_enumTypes[0].Descriptor()
}

func (WaveformMode) Type() protoreflect.EnumType {
	return &file_signage_proto_enumTypes[0]
}

func (x WaveformMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WaveformMode.Descriptor instead.
func (WaveformMode) EnumDescriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{0}
}

type DisplayInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Width              int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height             int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	ImageBufferAddress uint32                 `protobuf:"varint,3,opt,name=image_buffer_address,json=imageBufferAddress,proto3" json:"image_buffer_address,omitempty"`
	FirmwareVersion    string                 `protobuf:"bytes,4,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	LutVersion         string                 `protobuf:"bytes,5,opt,name=lut_version,json=lutVersion,proto3" json:"lut_version,omitempty"`
	AppVersion         string                 `protobuf:"bytes,6,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DisplayInfo) Reset() {
	*x = DisplayInfo{}
	mi := &file_signage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayInfo) ProtoMessage() {}

func (x *DisplayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_signage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayInfo.ProtoReflect.Descriptor instead.
func (*DisplayInfo) Descriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{0}
}

func (x *DisplayInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *DisplayInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *DisplayInfo) GetImageBufferAddress() uint32 {
	if x != nil {
		return x.ImageBufferAddress
	}
	return 0
}

func (x *DisplayInfo) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *DisplayInfo) GetLutVersion() string {
	if x != nil {
		return x.LutVersion
	}
	return ""
}

func (x *DisplayInfo) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

type Region struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	W             int32                  `protobuf:"varint,3,opt,name=w,proto3" json:"w,omitempty"`
	H             int32                  `protobuf:"varint,4,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_signage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_signage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{1}
}

func (x *Region) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Region) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Region) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *Region) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

type LoadImageHeader struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Mode   WaveformMode           `protobuf:"varint,1,opt,name=mode,proto3,enum=io.gosicp.gosignage.v1.WaveformMode" json:"mode,omitempty"`
	Region *Region                `protobuf:"bytes,2,opt,name=region,proto3,oneof" json:"region,omitempty"`
	// bits_per_pixel is one of 1, 2, 4, 8. Most signage flows use 4 (16
	// grayscale levels) for GC16/GL16, or 1 for DU/A2 fast modes.
	BitsPerPixel  int32 `protobuf:"varint,3,opt,name=bits_per_pixel,json=bitsPerPixel,proto3" json:"bits_per_pixel,omitempty"`
	TotalBytes    int64 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadImageHeader) Reset() {
	*x = LoadImageHeader{}
	mi := &file_signage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadImageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadImageHeader) ProtoMessage() {}

func (x *LoadImageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_signage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadImageHeader.ProtoReflect.Descriptor instead.
func (*LoadImageHeader) Descriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{2}
}

func (x *LoadImageHeader) GetMode() WaveformMode {
	if x != nil {
		return x.Mode
	}
	return WaveformMode_WAVEFORM_MODE_UNSPECIFIED
}

func (x *LoadImageHeader) GetRegion() *Region {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *LoadImageHeader) GetBitsPerPixel() int32 {
	if x != nil {
		return x.BitsPerPixel
	}
	return 0
}

func (x *LoadImageHeader) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type LoadImageChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*LoadImageChunk_Header
	//	*LoadImageChunk_Data
	Payload       isLoadImageChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadImageChunk) Reset() {
	*x = LoadImageChunk{}
	mi := &file_signage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadImageChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadImageChunk) ProtoMessage() {}

func (x *LoadImageChunk) ProtoReflect() protoreflect.Message {
	mi := &file_signage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadImageChunk.ProtoReflect.Descriptor instead.
func (*LoadImageChunk) Descriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{3}
}

func (x *LoadImageChunk) GetPayload() isLoadImageChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LoadImageChunk) GetHeader() *LoadImageHeader {
	if x != nil {
		if x, ok := x.Payload.(*LoadImageChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *LoadImageChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*LoadImageChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isLoadImageChunk_Payload interface {
	isLoadImageChunk_Payload()
}

type LoadImageChunk_Header struct {
	Header *LoadImageHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type LoadImageChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*LoadImageChunk_Header) isLoadImageChunk_Payload() {}

func (*LoadImageChunk_Data) isLoadImageChunk_Payload() {}

type LoadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameHash     string                 `protobuf:"bytes,1,opt,name=frame_hash,json=frameHash,proto3" json:"frame_hash,omitempty"`
	ElapsedMs     int64                  `protobuf:"varint,2,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadImageResponse) Reset() {
	*x = LoadImageResponse{}
	mi := &file_signage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadImageResponse) ProtoMessage() {}

func (x *LoadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadImageResponse.ProtoReflect.Descriptor instead.
func (*LoadImageResponse) Descriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{4}
}

func (x *LoadImageResponse) GetFrameHash() string {
	if x != nil {
		return x.FrameHash
	}
	return ""
}

func (x *LoadImageResponse) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          WaveformMode           `protobuf:"varint,1,opt,name=mode,proto3,enum=io.gosicp.gosignage.v1.WaveformMode" json:"mode,omitempty"`
	Region        *Region                `protobuf:"bytes,2,opt,name=region,proto3,oneof" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_signage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshRequest) GetMode() WaveformMode {
	if x != nil {
		return x.Mode
	}
	return WaveformMode_WAVEFORM_MODE_UNSPECIFIED
}

func (x *RefreshRequest) GetRegion() *Region {
	if x != nil {
		return x.Region
	}
	return nil
}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElapsedMs     int64                  `protobuf:"varint,1,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_signage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshResponse) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

type SetPullModeRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Enabled             bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ContentServerAddr   string                 `protobuf:"bytes,2,opt,name=content_server_addr,json=contentServerAddr,proto3" json:"content_server_addr,omitempty"`
	DeviceId            string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PollIntervalSeconds int32                  `protobuf:"varint,4,opt,name=poll_interval_seconds,json=pollIntervalSeconds,proto3" json:"poll_interval_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SetPullModeRequest) Reset() {
	*x = SetPullModeRequest{}
	mi := &file_signage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPullModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPullModeRequest) ProtoMessage() {}

func (x *SetPullModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPullModeRequest.ProtoReflect.Descriptor instead.
func (*SetPullModeRequest) Descriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{7}
}

func (x *SetPullModeRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SetPullModeRequest) GetContentServerAddr() string {
	if x != nil {
		return x.ContentServerAddr
	}
	return ""
}

func (x *SetPullModeRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SetPullModeRequest) GetPollIntervalSeconds() int32 {
	if x != nil {
		return x.PollIntervalSeconds
	}
	return 0
}

type PullModeStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Enabled             bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ContentServerAddr   string                 `protobuf:"bytes,2,opt,name=content_server_addr,json=contentServerAddr,proto3" json:"content_server_addr,omitempty"`
	DeviceId            string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PollIntervalSeconds int32                  `protobuf:"varint,4,opt,name=poll_interval_seconds,json=pollIntervalSeconds,proto3" json:"poll_interval_seconds,omitempty"`
	LastPullUnix        int64                  `protobuf:"varint,5,opt,name=last_pull_unix,json=lastPullUnix,proto3" json:"last_pull_unix,omitempty"`
	LastFrameHash       string                 `protobuf:"bytes,6,opt,name=last_frame_hash,json=lastFrameHash,proto3" json:"last_frame_hash,omitempty"`
	LastError           string                 `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PullModeStatus) Reset() {
	*x = PullModeStatus{}
	mi := &file_signage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullModeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullModeStatus) ProtoMessage() {}

func (x *PullModeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_signage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullModeStatus.ProtoReflect.Descriptor instead.
func (*PullModeStatus) Descriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{8}
}

func (x *PullModeStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PullModeStatus) GetContentServerAddr() string {
	if x != nil {
		return x.ContentServerAddr
	}
	return ""
}

func (x *PullModeStatus) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PullModeStatus) GetPollIntervalSeconds() int32 {
	if x != nil {
		return x.PollIntervalSeconds
	}
	return 0
}

func (x *PullModeStatus) GetLastPullUnix() int64 {
	if x != nil {
		return x.LastPullUnix
	}
	return 0
}

func (x *PullModeStatus) GetLastFrameHash() string {
	if x != nil {
		return x.LastFrameHash
	}
	return ""
}

func (x *PullModeStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type HealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceOpen      bool                   `protobuf:"varint,1,opt,name=device_open,json=deviceOpen,proto3" json:"device_open,omitempty"`
	LastError       string                 `protobuf:"bytes,2,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	ServerVersion   string                 `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	UptimeSeconds   int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	PullModeEnabled bool                   `protobuf:"varint,5,opt,name=pull_mode_enabled,json=pullModeEnabled,proto3" json:"pull_mode_enabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_signage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetDeviceOpen() bool {
	if x != nil {
		return x.DeviceOpen
	}
	return false
}

func (x *HealthResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *HealthResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthResponse) GetPullModeEnabled() bool {
	if x != nil {
		return x.PullModeEnabled
	}
	return false
}

type RotateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduledAtMs int64                  `protobuf:"varint,1,opt,name=scheduled_at_ms,json=scheduledAtMs,proto3" json:"scheduled_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateResponse) Reset() {
	*x = RotateResponse{}
	mi := &file_signage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateResponse) ProtoMessage() {}

func (x *RotateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateResponse.ProtoReflect.Descriptor instead.
func (*RotateResponse) Descriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{10}
}

func (x *RotateResponse) GetScheduledAtMs() int64 {
	if x != nil {
		return x.ScheduledAtMs
	}
	return 0
}

type ReissueClientCertResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ClientCertPem         string                 `protobuf:"bytes,1,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	ClientKeyPem          string                 `protobuf:"bytes,2,opt,name=client_key_pem,json=clientKeyPem,proto3" json:"client_key_pem,omitempty"`
	ClientCertFingerprint string                 `protobuf:"bytes,3,opt,name=client_cert_fingerprint,json=clientCertFingerprint,proto3" json:"client_cert_fingerprint,omitempty"`
	ServerRestartInMs     int64                  `protobuf:"varint,4,opt,name=server_restart_in_ms,json=serverRestartInMs,proto3" json:"server_restart_in_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReissueClientCertResponse) Reset() {
	*x = ReissueClientCertResponse{}
	mi := &file_signage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReissueClientCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReissueClientCertResponse) ProtoMessage() {}

func (x *ReissueClientCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReissueClientCertResponse.ProtoReflect.Descriptor instead.
func (*ReissueClientCertResponse) Descriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{11}
}

func (x *ReissueClientCertResponse) GetClientCertPem() string {
	if x != nil {
		return x.ClientCertPem
	}
	return ""
}

func (x *ReissueClientCertResponse) GetClientKeyPem() string {
	if x != nil {
		return x.ClientKeyPem
	}
	return ""
}

func (x *ReissueClientCertResponse) GetClientCertFingerprint() string {
	if x != nil {
		return x.ClientCertFingerprint
	}
	return ""
}

func (x *ReissueClientCertResponse) GetServerRestartInMs() int64 {
	if x != nil {
		return x.ServerRestartInMs
	}
	return 0
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromText      string                 `protobuf:"bytes,1,opt,name=prom_text,json=promText,proto3" json:"prom_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_signage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{12}
}

func (x *GetMetricsResponse) GetPromText() string {
	if x != nil {
		return x.PromText
	}
	return ""
}

type GetFrameRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceId         string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	CurrentFrameHash string                 `protobuf:"bytes,2,opt,name=current_frame_hash,json=currentFrameHash,proto3" json:"current_frame_hash,omitempty"`
	WidthHint        int32                  `protobuf:"varint,3,opt,name=width_hint,json=widthHint,proto3" json:"width_hint,omitempty"`
	HeightHint       int32                  `protobuf:"varint,4,opt,name=height_hint,json=heightHint,proto3" json:"height_hint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetFrameRequest) Reset() {
	*x = GetFrameRequest{}
	mi := &file_signage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrameRequest) ProtoMessage() {}

func (x *GetFrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrameRequest.ProtoReflect.Descriptor instead.
func (*GetFrameRequest) Descriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{13}
}

func (x *GetFrameRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetFrameRequest) GetCurrentFrameHash() string {
	if x != nil {
		return x.CurrentFrameHash
	}
	return ""
}

func (x *GetFrameRequest) GetWidthHint() int32 {
	if x != nil {
		return x.WidthHint
	}
	return 0
}

func (x *GetFrameRequest) GetHeightHint() int32 {
	if x != nil {
		return x.HeightHint
	}
	return 0
}

type GetFrameResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Unchanged       bool                   `protobuf:"varint,1,opt,name=unchanged,proto3" json:"unchanged,omitempty"`
	FrameHash       string                 `protobuf:"bytes,2,opt,name=frame_hash,json=frameHash,proto3" json:"frame_hash,omitempty"`
	Png             []byte                 `protobuf:"bytes,3,opt,name=png,proto3" json:"png,omitempty"`
	NextPollSeconds int32                  `protobuf:"varint,4,opt,name=next_poll_seconds,json=nextPollSeconds,proto3" json:"next_poll_seconds,omitempty"`
	SuggestedMode   WaveformMode           `protobuf:"varint,5,opt,name=suggested_mode,json=suggestedMode,proto3,enum=io.gosicp.gosignage.v1.WaveformMode" json:"suggested_mode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetFrameResponse) Reset() {
	*x = GetFrameResponse{}
	mi := &file_signage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrameResponse) ProtoMessage() {}

func (x *GetFrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrameResponse.ProtoReflect.Descriptor instead.
func (*GetFrameResponse) Descriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{14}
}

func (x *GetFrameResponse) GetUnchanged() bool {
	if x != nil {
		return x.Unchanged
	}
	return false
}

func (x *GetFrameResponse) GetFrameHash() string {
	if x != nil {
		return x.FrameHash
	}
	return ""
}

func (x *GetFrameResponse) GetPng() []byte {
	if x != nil {
		return x.Png
	}
	return nil
}

func (x *GetFrameResponse) GetNextPollSeconds() int32 {
	if x != nil {
		return x.NextPollSeconds
	}
	return 0
}

func (x *GetFrameResponse) GetSuggestedMode() WaveformMode {
	if x != nil {
		return x.SuggestedMode
	}
	return WaveformMode_WAVEFORM_MODE_UNSPECIFIED
}

type ReportStatusRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceId         string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	CurrentFrameHash string                 `protobuf:"bytes,2,opt,name=current_frame_hash,json=currentFrameHash,proto3" json:"current_frame_hash,omitempty"`
	FirmwareVersion  string                 `protobuf:"bytes,3,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	LutVersion       string                 `protobuf:"bytes,4,opt,name=lut_version,json=lutVersion,proto3" json:"lut_version,omitempty"`
	PanelWidth       int32                  `protobuf:"varint,5,opt,name=panel_width,json=panelWidth,proto3" json:"panel_width,omitempty"`
	PanelHeight      int32                  `protobuf:"varint,6,opt,name=panel_height,json=panelHeight,proto3" json:"panel_height,omitempty"`
	AppVersion       string                 `protobuf:"bytes,7,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	LastError        string                 `protobuf:"bytes,8,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	UptimeSeconds    int64                  `protobuf:"varint,9,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReportStatusRequest) Reset() {
	*x = ReportStatusRequest{}
	mi := &file_signage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusRequest) ProtoMessage() {}

func (x *ReportStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportStatusRequest) Descriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{15}
}

func (x *ReportStatusRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ReportStatusRequest) GetCurrentFrameHash() string {
	if x != nil {
		return x.CurrentFrameHash
	}
	return ""
}

func (x *ReportStatusRequest) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *ReportStatusRequest) GetLutVersion() string {
	if x != nil {
		return x.LutVersion
	}
	return ""
}

func (x *ReportStatusRequest) GetPanelWidth() int32 {
	if x != nil {
		return x.PanelWidth
	}
	return 0
}

func (x *ReportStatusRequest) GetPanelHeight() int32 {
	if x != nil {
		return x.PanelHeight
	}
	return 0
}

func (x *ReportStatusRequest) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *ReportStatusRequest) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *ReportStatusRequest) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type ReportStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NextReportSeconds int32                  `protobuf:"varint,1,opt,name=next_report_seconds,json=nextReportSeconds,proto3" json:"next_report_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReportStatusResponse) Reset() {
	*x = ReportStatusResponse{}
	mi := &file_signage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusResponse) ProtoMessage() {}

func (x *ReportStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportStatusResponse) Descriptor() ([]byte, []int) {
	return file_signage_proto_rawDescGZIP(), []int{16}
}

func (x *ReportStatusResponse) GetNextReportSeconds() int32 {
	if x != nil {
		return x.NextReportSeconds
	}
	return 0
}

var File_signage_proto protoreflect.FileDescriptor

const file_signage_proto_rawDesc = "" +
	"\n" +
	"\rsignage.proto\x12\x16io.gosicp.gosignage.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xda\x01\n" +
	"\vDisplayInfo\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x120\n" +
	"\x14image_buffer_address\x18\x03 \x01(\rR\x12imageBufferAddress\x12)\n" +
	"\x10firmware_version\x18\x04 \x01(\tR\x0ffirmwareVersion\x12\x1f\n" +
	"\vlut_version\x18\x05 \x01(\tR\n" +
	"lutVersion\x12\x1f\n" +
	"\vapp_version\x18\x06 \x01(\tR\n" +
	"appVersion\"@\n" +
	"\x06Region\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\f\n" +
	"\x01w\x18\x03 \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\x04 \x01(\x05R\x01h\"\xda\x01\n" +
	"\x0fLoadImageHeader\x128\n" +
	"\x04mode\x18\x01 \x01(\x0e2$.io.gosicp.gosignage.v1.WaveformModeR\x04mode\x12;\n" +
	"\x06region\x18\x02 \x01(\v2\x1e.io.gosicp.gosignage.v1.RegionH\x00R\x06region\x88\x01\x01\x12$\n" +
	"\x0ebits_per_pixel\x18\x03 \x01(\x05R\fbitsPerPixel\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytesB\t\n" +
	"\a_region\"t\n" +
	"\x0eLoadImageChunk\x12A\n" +
	"\x06header\x18\x01 \x01(\v2'.io.gosicp.gosignage.v1.LoadImageHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"Q\n" +
	"\x11LoadImageResponse\x12\x1d\n" +
	"\n" +
	"frame_hash\x18\x01 \x01(\tR\tframeHash\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x02 \x01(\x03R\telapsedMs\"\x92\x01\n" +
	"\x0eRefreshRequest\x128\n" +
	"\x04mode\x18\x01 \x01(\x0e2$.io.gosicp.gosignage.v1.WaveformModeR\x04mode\x12;\n" +
	"\x06region\x18\x02 \x01(\v2\x1e.io.gosicp.gosignage.v1.RegionH\x00R\x06region\x88\x01\x01B\t\n" +
	"\a_region\"0\n" +
	"\x0fRefreshResponse\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x01 \x01(\x03R\telapsedMs\"\xaf\x01\n" +
	"\x12SetPullModeRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12.\n" +
	"\x13content_server_addr\x18\x02 \x01(\tR\x11contentServerAddr\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x122\n" +
	"\x15poll_interval_seconds\x18\x04 \x01(\x05R\x13pollIntervalSeconds\"\x98\x02\n" +
	"\x0ePullModeStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12.\n" +
	"\x13content_server_addr\x18\x02 \x01(\tR\x11contentServerAddr\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x122\n" +
	"\x15poll_interval_seconds\x18\x04 \x01(\x05R\x13pollIntervalSeconds\x12$\n" +
	"\x0elast_pull_unix\x18\x05 \x01(\x03R\flastPullUnix\x12&\n" +
	"\x0flast_frame_hash\x18\x06 \x01(\tR\rlastFrameHash\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\"\xca\x01\n" +
	"\x0eHealthResponse\x12\x1f\n" +
	"\vdevice_open\x18\x01 \x01(\bR\n" +
	"deviceOpen\x12\x1d\n" +
	"\n" +
	"last_error\x18\x02 \x01(\tR\tlastError\x12%\n" +
	"\x0eserver_version\x18\x03 \x01(\tR\rserverVersion\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12*\n" +
	"\x11pull_mode_enabled\x18\x05 \x01(\bR\x0fpullModeEnabled\"8\n" +
	"\x0eRotateResponse\x12&\n" +
	"\x0fscheduled_at_ms\x18\x01 \x01(\x03R\rscheduledAtMs\"\xd2\x01\n" +
	"\x19ReissueClientCertResponse\x12&\n" +
	"\x0fclient_cert_pem\x18\x01 \x01(\tR\rclientCertPem\x12$\n" +
	"\x0eclient_key_pem\x18\x02 \x01(\tR\fclientKeyPem\x126\n" +
	"\x17client_cert_fingerprint\x18\x03 \x01(\tR\x15clientCertFingerprint\x12/\n" +
	"\x14server_restart_in_ms\x18\x04 \x01(\x03R\x11serverRestartInMs\"1\n" +
	"\x12GetMetricsResponse\x12\x1b\n" +
	"\tprom_text\x18\x01 \x01(\tR\bpromText\"\x9c\x01\n" +
	"\x0fGetFrameRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12,\n" +
	"\x12current_frame_hash\x18\x02 \x01(\tR\x10currentFrameHash\x12\x1d\n" +
	"\n" +
	"width_hint\x18\x03 \x01(\x05R\twidthHint\x12\x1f\n" +
	"\vheight_hint\x18\x04 \x01(\x05R\n" +
	"heightHint\"\xda\x01\n" +
	"\x10GetFrameResponse\x12\x1c\n" +
	"\tunchanged\x18\x01 \x01(\bR\tunchanged\x12\x1d\n" +
	"\n" +
	"frame_hash\x18\x02 \x01(\tR\tframeHash\x12\x10\n" +
	"\x03png\x18\x03 \x01(\fR\x03png\x12*\n" +
	"\x11next_poll_seconds\x18\x04 \x01(\x05R\x0fnextPollSeconds\x12K\n" +
	"\x0esuggested_mode\x18\x05 \x01(\x0e2$.io.gosicp.gosignage.v1.WaveformModeR\rsuggestedMode\"\xd7\x02\n" +
	"\x13ReportStatusRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12,\n" +
	"\x12current_frame_hash\x18\x02 \x01(\tR\x10currentFrameHash\x12)\n" +
	"\x10firmware_version\x18\x03 \x01(\tR\x0ffirmwareVersion\x12\x1f\n" +
	"\vlut_version\x18\x04 \x01(\tR\n" +
	"lutVersion\x12\x1f\n" +
	"\vpanel_width\x18\x05 \x01(\x05R\n" +
	"panelWidth\x12!\n" +
	"\fpanel_height\x18\x06 \x01(\x05R\vpanelHeight\x12\x1f\n" +
	"\vapp_version\x18\a \x01(\tR\n" +
	"appVersion\x12\x1d\n" +
	"\n" +
	"last_error\x18\b \x01(\tR\tlastError\x12%\n" +
	"\x0euptime_seconds\x18\t \x01(\x03R\ruptimeSeconds\"F\n" +
	"\x14ReportStatusResponse\x12.\n" +
	"\x13next_report_seconds\x18\x01 \x01(\x05R\x11nextReportSeconds*\xd3\x01\n" +
	"\fWaveformMode\x12\x1d\n" +
	"\x19WAVEFORM_MODE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12WAVEFORM_MODE_INIT\x10\x01\x12\x14\n" +
	"\x10WAVEFORM_MODE_DU\x10\x02\x12\x16\n" +
	"\x12WAVEFORM_MODE_GC16\x10\x03\x12\x16\n" +
	"\x12WAVEFORM_MODE_GL16\x10\x04\x12\x17\n" +
	"\x13WAVEFORM_MODE_GLR16\x10\x05\x12\x17\n" +
	"\x13WAVEFORM_MODE_GLD16\x10\x06\x12\x14\n" +
	"\x10WAVEFORM_MODE_A2\x10\a2\xeb\x06\n" +
	"\aDisplay\x12F\n" +
	"\aGetInfo\x12\x16.google.protobuf.Empty\x1a#.io.gosicp.gosignage.v1.DisplayInfo\x12H\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a&.io.gosicp.gosignage.v1.HealthResponse\x12`\n" +
	"\tLoadImage\x12&.io.gosicp.gosignage.v1.LoadImageChunk\x1a).io.gosicp.gosignage.v1.LoadImageResponse(\x01\x12Z\n" +
	"\aRefresh\x12&.io.gosicp.gosignage.v1.RefreshRequest\x1a'.io.gosicp.gosignage.v1.RefreshResponse\x127\n" +
	"\x05Sleep\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x129\n" +
	"\aStandby\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\vSetPullMode\x12*.io.gosicp.gosignage.v1.SetPullModeRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\vGetPullMode\x12\x16.google.protobuf.Empty\x1a&.io.gosicp.gosignage.v1.PullModeStatus\x12H\n" +
	"\x06Rotate\x12\x16.google.protobuf.Empty\x1a&.io.gosicp.gosignage.v1.RotateResponse\x12^\n" +
	"\x11ReissueClientCert\x12\x16.google.protobuf.Empty\x1a1.io.gosicp.gosignage.v1.ReissueClientCertResponse\x12P\n" +
	"\n" +
	"GetMetrics\x12\x16.google.protobuf.Empty\x1a*.io.gosicp.gosignage.v1.GetMetricsResponse2\xd3\x01\n" +
	"\aContent\x12]\n" +
	"\bGetFrame\x12'.io.gosicp.gosignage.v1.GetFrameRequest\x1a(.io.gosicp.gosignage.v1.GetFrameResponse\x12i\n" +
	"\fReportStatus\x12+.io.gosicp.gosignage.v1.ReportStatusRequest\x1a,.io.gosicp.gosignage.v1.ReportStatusResponseB9Z7github.com/go-sicp/go-signage/signageproto;signageprotob\x06proto3"

var (
	file_signage_proto_rawDescOnce sync.Once
	file_signage_proto_rawDescData []byte
)

func file_signage_proto_rawDescGZIP() []byte {
	file_signage_proto_rawDescOnce.Do(func() {
		file_signage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signage_proto_rawDesc), len(file_signage_proto_rawDesc)))
	})
	return file_signage_proto_rawDescData
}

var file_signage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_signage_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_signage_proto_goTypes = []any{
	(WaveformMode)(0),                 // 0: io.gosicp.gosignage.v1.WaveformMode
	(*DisplayInfo)(nil),               // 1: io.gosicp.gosignage.v1.DisplayInfo
	(*Region)(nil),                    // 2: io.gosicp.gosignage.v1.Region
	(*LoadImageHeader)(nil),           // 3: io.gosicp.gosignage.v1.LoadImageHeader
	(*LoadImageChunk)(nil),            // 4: io.gosicp.gosignage.v1.LoadImageChunk
	(*LoadImageResponse)(nil),         // 5: io.gosicp.gosignage.v1.LoadImageResponse
	(*RefreshRequest)(nil),            // 6: io.gosicp.gosignage.v1.RefreshRequest
	(*RefreshResponse)(nil),           // 7: io.gosicp.gosignage.v1.RefreshResponse
	(*SetPullModeRequest)(nil),        // 8: io.gosicp.gosignage.v1.SetPullModeRequest
	(*PullModeStatus)(nil),            // 9: io.gosicp.gosignage.v1.PullModeStatus
	(*HealthResponse)(nil),            // 10: io.gosicp.gosignage.v1.HealthResponse
	(*RotateResponse)(nil),            // 11: io.gosicp.gosignage.v1.RotateResponse
	(*ReissueClientCertResponse)(nil), // 12: io.gosicp.gosignage.v1.ReissueClientCertResponse
	(*GetMetricsResponse)(nil),        // 13: io.gosicp.gosignage.v1.GetMetricsResponse
	(*GetFrameRequest)(nil),           // 14: io.gosicp.gosignage.v1.GetFrameRequest
	(*GetFrameResponse)(nil),          // 15: io.gosicp.gosignage.v1.GetFrameResponse
	(*ReportStatusRequest)(nil),       // 16: io.gosicp.gosignage.v1.ReportStatusRequest
	(*ReportStatusResponse)(nil),      // 17: io.gosicp.gosignage.v1.ReportStatusResponse
	(*emptypb.Empty)(nil),             // 18: google.protobuf.Empty
}
var file_signage_proto_depIdxs = []int32{
	0,  // 0: io.gosicp.gosignage.v1.LoadImageHeader.mode:type_name -> io.gosicp.gosignage.v1.WaveformMode
	2,  // 1: io.gosicp.gosignage.v1.LoadImageHeader.region:type_name -> io.gosicp.gosignage.v1.Region
	3,  // 2: io.gosicp.gosignage.v1.LoadImageChunk.header:type_name -> io.gosicp.gosignage.v1.LoadImageHeader
	0,  // 3: io.gosicp.gosignage.v1.RefreshRequest.mode:type_name -> io.gosicp.gosignage.v1.WaveformMode
	2,  // 4: io.gosicp.gosignage.v1.RefreshRequest.region:type_name -> io.gosicp.gosignage.v1.Region
	0,  // 5: io.gosicp.gosignage.v1.GetFrameResponse.suggested_mode:type_name -> io.gosicp.gosignage.v1.WaveformMode
	18, // 6: io.gosicp.gosignage.v1.Display.GetInfo:input_type -> google.protobuf.Empty
	18, // 7: io.gosicp.gosignage.v1.Display.Health:input_type -> google.protobuf.Empty
	4,  // 8: io.gosicp.gosignage.v1.Display.LoadImage:input_type -> io.gosicp.gosignage.v1.LoadImageChunk
	6,  // 9: io.gosicp.gosignage.v1.Display.Refresh:input_type -> io.gosicp.gosignage.v1.RefreshRequest
	18, // 10: io.gosicp.gosignage.v1.Display.Sleep:input_type -> google.protobuf.Empty
	18, // 11: io.gosicp.gosignage.v1.Display.Standby:input_type -> google.protobuf.Empty
	8,  // 12: io.gosicp.gosignage.v1.Display.SetPullMode:input_type -> io.gosicp.gosignage.v1.SetPullModeRequest
	18, // 13: io.gosicp.gosignage.v1.Display.GetPullMode:input_type -> google.protobuf.Empty
	18, // 14: io.gosicp.gosignage.v1.Display.Rotate:input_type -> google.protobuf.Empty
	18, // 15: io.gosicp.gosignage.v1.Display.ReissueClientCert:input_type -> google.protobuf.Empty
	18, // 16: io.gosicp.gosignage.v1.Display.GetMetrics:input_type -> google.protobuf.Empty
	14, // 17: io.gosicp.gosignage.v1.Content.GetFrame:input_type -> io.gosicp.gosignage.v1.GetFrameRequest
	16, // 18: io.gosicp.gosignage.v1.Content.ReportStatus:input_type -> io.gosicp.gosignage.v1.ReportStatusRequest
	1,  // 19: io.gosicp.gosignage.v1.Display.GetInfo:output_type -> io.gosicp.gosignage.v1.DisplayInfo
	10, // 20: io.gosicp.gosignage.v1.Display.Health:output_type -> io.gosicp.gosignage.v1.HealthResponse
	5,  // 21: io.gosicp.gosignage.v1.Display.LoadImage:output_type -> io.gosicp.gosignage.v1.LoadImageResponse
	7,  // 22: io.gosicp.gosignage.v1.Display.Refresh:output_type -> io.gosicp.gosignage.v1.RefreshResponse
	18, // 23: io.gosicp.gosignage.v1.Display.Sleep:output_type -> google.protobuf.Empty
	18, // 24: io.gosicp.gosignage.v1.Display.Standby:output_type -> google.protobuf.Empty
	18, // 25: io.gosicp.gosignage.v1.Display.SetPullMode:output_type -> google.protobuf.Empty
	9,  // 26: io.gosicp.gosignage.v1.Display.GetPullMode:output_type -> io.gosicp.gosignage.v1.PullModeStatus
	11, // 27: io.gosicp.gosignage.v1.Display.Rotate:output_type -> io.gosicp.gosignage.v1.RotateResponse
	12, // 28: io.gosicp.gosignage.v1.Display.ReissueClientCert:output_type -> io.gosicp.gosignage.v1.ReissueClientCertResponse
	13, // 29: io.gosicp.gosignage.v1.Display.GetMetrics:output_type -> io.gosicp.gosignage.v1.GetMetricsResponse
	15, // 30: io.gosicp.gosignage.v1.Content.GetFrame:output_type -> io.gosicp.gosignage.v1.GetFrameResponse
	17, // 31: io.gosicp.gosignage.v1.Content.ReportStatus:output_type -> io.gosicp.gosignage.v1.ReportStatusResponse
	19, // [19:32] is the sub-list for method output_type
	6,  // [6:19] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_signage_proto_init() }
func file_signage_proto_init() {
	if File_signage_proto != nil {
		return
	}
	file_signage_proto_msgTypes[2].OneofWrappers = []any{}
	file_signage_proto_msgTypes[3].OneofWrappers = []any{
		(*LoadImageChunk_Header)(nil),
		(*LoadImageChunk_Data)(nil),
	}
	file_signage_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signage_proto_rawDesc), len(file_signage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_signage_proto_goTypes,
		DependencyIndexes: file_signage_proto_depIdxs,
		EnumInfos:         file_signage_proto_enumTypes,
		MessageInfos:      file_signage_proto_msgTypes,
	}.Build()
	File_signage_proto = out.File
	file_signage_proto_goTypes = nil
	file_signage_proto_depIdxs = nil
}
